### PR TITLE
x86/hex0: Shrink code size from 256 -> 190 bytes

### PR DESCRIPTION
**Pull request by goldsteinn**
IIUC the goal is to make this small so thought I'd have some fun with it.

Tested on its, hex1 and a few other cases.

NB: We could save another 5-10 bytes if we assumed linux (or any OS that zeros many of the registers before jumping to `_start`).

### CODE REVIEW

**Comment by goldsteinn** [comment]
ping @stikona & @oriansj

**Comment by oriansj** [comment]
@goldsteinn thank you for your work (sorry it took me so long to review) but it is excellent

**Comment by stikonas** [comment]
@oriansj have you merged this to stage0-posix-x86?

**Comment by stikonas** [comment]
@goldsteinn could you also update the following files:
* https://github.com/oriansj/stage0-posix-x86/blob/master/GAS/hex0_x86.S
* https://github.com/oriansj/stage0-posix-x86/blob/master/Development/hex0_x86.M1
* https://github.com/oriansj/stage0-posix-x86/blob/master/hex0_x86.hex0

**Comment by stikonas** [comment]
And regarding non-zeroed registers, probably best not to do it. We also want to run this on very simple kernels, I don't think [builder-hex0](https://github.com/ironmeld/builder-hex0) does any register zeroing.

**Comment by stikonas** [comment]
> @goldsteinn could you also update the following files:
>     * https://github.com/oriansj/stage0-posix-x86/blob/master/GAS/hex0_x86.S
>     * https://github.com/oriansj/stage0-posix-x86/blob/master/Development/hex0_x86.M1
>     * https://github.com/oriansj/stage0-posix-x86/blob/master/hex0_x86.hex0

I guess I'll update these in stage0-posix-x86 repo myself (so that I can also review the new way).

**Comment by goldsteinn** [comment]
> > @goldsteinn could you also update the following files:
> > * https://github.com/oriansj/stage0-posix-x86/blob/master/GAS/hex0_x86.S
> > * https://github.com/oriansj/stage0-posix-x86/blob/master/Development/hex0_x86.M1
> > * https://github.com/oriansj/stage0-posix-x86/blob/master/hex0_x86.hex0
> 
> I guess I'll update these in stage0-posix-x86 repo myself (so that I can also review the new way).

Hi, I'm happy to propagate the above files. I'm out of town for the next few days.
Which files (if any) are still outstanding after your patch?

**Comment by stikonas** [comment]
> > > @goldsteinn could you also update the following files:
> > > 
> > > * https://github.com/oriansj/stage0-posix-x86/blob/master/GAS/hex0_x86.S
> > > * https://github.com/oriansj/stage0-posix-x86/blob/master/Development/hex0_x86.M1
> > > * https://github.com/oriansj/stage0-posix-x86/blob/master/hex0_x86.hex0
> > 
> > 
> > I guess I'll update these in stage0-posix-x86 repo myself (so that I can also review the new way).
> 
> Hi, I'm happy to propagate the above files. I'm out of town for the next few days. Which files (if any) are still outstanding after your patch?

I've done all 3 of them and update changelogs. So we are fine now.

(That said, if you like this, you can always look at other things here, we have kaem seed, other arches, and various baremetal non-POSIX seeds too)

**Comment by goldsteinn** [comment]
> > > > @goldsteinn could you also update the following files:
> > > > 
> > > > * https://github.com/oriansj/stage0-posix-x86/blob/master/GAS/hex0_x86.S
> > > > * https://github.com/oriansj/stage0-posix-x86/blob/master/Development/hex0_x86.M1
> > > > * https://github.com/oriansj/stage0-posix-x86/blob/master/hex0_x86.hex0
> > > 
> > > 
> > > I guess I'll update these in stage0-posix-x86 repo myself (so that I can also review the new way).
> > 
> > 
> > Hi, I'm happy to propagate the above files. I'm out of town for the next few days. Which files (if any) are still outstanding after your patch?
> 
> I've done all 3 of them and update changelogs. So we are fine now.
> 
> (That said, if you like this, you can always look at other things here, we have kaem seed, other arches, and various baremetal non-POSIX seeds too)

I saw the bare metal ones, although since they need to be 512 bytes and already meet that threshold, there doesn't seem to be much reason. I might take a look at aarch64.

**Comment by stikonas** [comment]
Aarch64 support in general would probably benefit from reworking in riscv style that uses fixed word size instructions. Though the distinction only becomes apparent at hex2.

**Comment by stikonas** [comment]
Aarch64 support in general would probably benefit from reworking in riscv style that uses fixed word size instructions. Though the distinction only becomes apparent at hex2.

**Pull request merged**
