### PR TITLE
Add documentation and builder-hex0-x86-stage1 seed.

### LINKED ISSUE #38: Add builder-hex0-x86-stage1.bin bootstrap seed
It has been suggested that the bootstrap seed for kernel bootstrapping in live-bootstrap be added to this project.

The file is builder-hex0-x86-stage1.bin which can be found in this PR: https://github.com/fosslinux/live-bootstrap/pull/295

I am not sure if this is the right place but I don't have any problem with it if it make sense to you.

I would put the file in NATIVE/x86 directory along with the source file builder-hex0-x86-stage1.hex0. I am open to using a different directory. I can also rename the binary to use the img extension if that is preferred.

The thing is: the bootstrap seed file is primarily a boot loader for builder-hex0-x86-stage2.hex0. It compiles stage2 into address 0x7E00 and then jumps to it. So, the seed is not useful by itself for creating a compiler (hex0) or shell (kaem). I could include the builder-hex0-x86-stage2.hex0 here source as well. Stage2 can compile any hex0 file and write it back to disk so in combination with the boot loader it forms a useful bootstrap. But I'm not sure if it makes sense to include a 75K kernel source file in this bootstrap-seed repository. Please let me know your thoughts on this.

Note that I won't be able to use this in live-bootstrap until stage0-posix pulls in a new bootstrap-seeds so that would need to be done as well.

I can provide a PR based on your advice or if you want to make the change feel free.

### PR DESCRIPTION
**Pull request by rick-masters**
Closes #38

### CODE REVIEW

**Comment by stikonas** [comment]
Is it worth providing full sector image with MBR bytes at the end?

**Comment by rick-masters** [comment]
@stikonas I think I'll just go ahead and pad the source and binary with zeros and the MBR bytes. I'll also rename it with an `img` extension to be consistent with stage0_monitor.

In retrospect, providing a 200 byte binary is more marketing than technically useful since it has to be padded anyway. But the point has been made and it will be more usable if changed to 512 bytes.

**Comment by stikonas** [comment]
We could still market it as 200 non zero bytes...

**Comment by rick-masters** [comment]
@stikonas I'll say it's "a binary seed with 200 bytes of code"

**Pull request merged**
